export const FETCH_LOCATION_REQUEST = "location:FETCH_LOCATION_REQUEST";
export const FETCH_LOCATION_FAILURE = "location:FETCH_LOCATION_FAILURE";
export const FETCH_LOCATION_SUCCESS = "location:FETCH_LOCATION_SUCCESS";