export const FETCH_COLLECTION_POINTS_REQUEST = "collectionpoints:FETCH_COLLECTION_POINTS_REQUEST";
export const FETCH_COLLECTION_POINTS_FAILURE = "collectionpoints:FETCH_COLLECTION_POINTS_FAILURE";
export const FETCH_COLLECTION_POINTS_SUCCESS = "collectionpoints:FETCH_COLLECTION_POINTS_SUCCESS";

export const USER_CANNOT_CREATE_ORDER = "collectionpoints:FETCH_COLLECTION_POINTS_SUCCESS";