export const RESET_PASSWORD_REQUEST: "auth:RESET_PASSWORD_REQUEST" =
  "auth:RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS: "auth:RESET_PASSWORD_SUCCESS" =
  "auth:RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE: "auth:RESET_PASSWORD_FAILURE" =
  "auth:RESET_PASSWORD_FAILURE";
